### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Pussydestroyer69DK** [TAAPArthur/CrunchyrollGuestPassFinder#5] opened 2020-10-21 17:20 UTC
Hello again,
When I try to run the bot in any way, shape, or form it makes a TypeError

`C:\Users\Roni Temizsoy>python "C:\Users\Roni Temizsoy\Desktop\CrunchyrollGuestPassFinder- 
 master\CrunchyrollGuestPassFinder-master\crunchyroll-guest-pass-finder.py"`
`Username:itzrondy`
`INFO:logged into itzrondy`
`Traceback (most recent call last):
 File "C:\Users\Roni Temizsoy\Desktop\CrunchyrollGuestPassFinder-master\CrunchyrollGuestPassFinder-master\crunchyroll- 
 guest-pass-finder.py", line 228, in <module>`
`if crunchyrollGuestPassFinder.isAccountNonPremium():`
`File "C:\Users\Roni Temizsoy\Desktop\CrunchyrollGuestPassFinder-master\CrunchyrollGuestPassFinder-master\crunchyroll- 
 guest-pass-finder.py", line 68, in isAccountNonPremium`
`return not r.json()['data']["user"]['premium']`
`TypeError: 'NoneType' object is not subscriptable`

**Comment by TAAPArthur** [comment] 2020-11-01 01:29
Can reproduce this error. Looks like Crunchyroll changed their api.

**Comment by TAAPArthur** [comment] 2020-11-06 02:35
I think a patch like this will solve the issue. `isAccountNonPremium` is used to as a signal to exit the program so at the very least the script will run and activate your account. Currently verifying that it still will detect the when an account becomes premium and if it does will push the fix. 
```
diff --git a/crunchyroll-guest-pass-finder.py b/crunchyroll-guest-pass-finder.py
index 94f509b..4751611 100755
--- a/crunchyroll-guest-pass-finder.py
+++ b/crunchyroll-guest-pass-finder.py
@@ -65,7 +65,7 @@ class CrunchyrollGuestPassFinder():
 
     def isAccountNonPremium(self):
         r = self.session.get(self.api_auth_url.format(self.session_id))
-        return not r.json()['data']["user"]['premium']
+        return not r.json() or not r.json()['data']["user"]['premium']
 
     def get_from_data(self, url, formClassName):
         r = self.session.get(url)
```

**Comment by Pussydestroyer69DK** [comment] 2020-11-06 09:30
> I think a patch like this will solve the issue. `isAccountNonPremium` is used to as a signal to exit the program so at the very least the script will run and activate your account. Currently verifying that it still will detect the when an account becomes premium and if it does will push the fix.
> 
> ```
> diff --git a/crunchyroll-guest-pass-finder.py b/crunchyroll-guest-pass-finder.py
> index 94f509b..4751611 100755
> --- a/crunchyroll-guest-pass-finder.py
> +++ b/crunchyroll-guest-pass-finder.py
> @@ -65,7 +65,7 @@ class CrunchyrollGuestPassFinder():
>  
>      def isAccountNonPremium(self):
>          r = self.session.get(self.api_auth_url.format(self.session_id))
> -        return not r.json()['data']["user"]['premium']
> +        return not r.json() or not r.json()['data']["user"]['premium']
>  
>      def get_from_data(self, url, formClassName):
>          r = self.session.get(url)
> ```

Are you gonna update the files or am i supposed to update my own files. I am confused. Sorry if it is a stupid question.

**Comment by TAAPArthur** [comment] 2020-11-07 02:42
I'll update the package and close the issue once I confirm this fixes the issue. Started running it last night and the fish don't seem to be biting. Just sharing the suggested fix in case you didn't want to wait a few (more) days.

**Closed** 2020-11-16 07:45 UTC
Labels: bug, confirmed
